apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: company-api-flux
spec:
  template:
    spec:
      containers:
        - name: workload
          volumeMounts: 
            - name: custom-vars
              mountPath: /etc/config
      volumes:
        - configMap:
            name: custom-vars
          name: custom-vars